export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";


export const RETRIEVE_CATEGORIAS = "RETRIEVE_CATEGORIAS";
export const DELETE_CATEGORIA = "DELETE_CATEGORIA";
export const CREATE_CATEGORIA = "CREATE_CATEGORIA";
export const UPDATE_CATEGORIA = "UPDATE_CATEGORIA";

export const RETRIEVE_TAREAS = "RETRIEVE_TAREAS";
export const DELETE_TAREA = "DELETE_TAREA";
export const CREATE_TAREA = "CREATE_TAREA";
export const UPDATE_TAREA = "UPDATE_TAREA";

export const RETRIEVE_SETTINGS = "RETRIEVE_SETTINGS";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
